frr version 10.5.1
frr defaults traditional
hostname br
log syslog notifications
log timestamp precision 3
no log unique-id
service integrated-vtysh-config
!
ip route 0.0.0.0/0 100.1.0.254
!
vrf Mgmt
exit-vrf
!
interface eth2
 ip address 100.1.0.1/24
exit
!
end
