frr version 10.5.1
frr defaults traditional
hostname vyos2
log syslog notifications
log timestamp precision 3
no log unique-id
service integrated-vtysh-config
!
interface eth1
 ip address 10.1.0.2/24
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.2.0.2/24
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 10.3.0.254/24
 ip ospf network point-to-point
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0.0.0.0
 network 10.0.0.0/8 area 0.0.0.0
exit
!
mpls ldp
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
 exit-address-family
 !
exit
!
end
