frr version 10.5.1
frr defaults traditional
hostname vyos2
log syslog notifications
log timestamp precision 3
no log unique-id
service integrated-vtysh-config
!
interface eth1
 ip address 10.3.0.3/24
 ip ospf network point-to-point
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0.0.0.0
 network 10.0.0.0/8 area 0.0.0.0
exit
!
mpls ldp
 !
 address-family ipv4
  discovery transport-address 3.3.3.3
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
end
