frr version 10.5.1
frr defaults traditional
hostname vyos3
log syslog notifications
log timestamp precision 3
no log unique-id
service integrated-vtysh-config
!
vrf ent
exit-vrf
!
interface eth1
 ip address 10.2.0.3/24
 ip ospf network point-to-point
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router bgp 1 vrf ent
 no bgp ebgp-requires-policy
 no bgp reject-as-sets
 no bgp default ipv4-unicast
 no bgp network import-check
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 100:1
  rt vpn both 100:1
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 1
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 no bgp reject-as-sets
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor 1.1.1.1 remote-as 1
 no neighbor 1.1.1.1 enforce-first-as
 neighbor 1.1.1.1 update-source lo
 !
 address-family ipv4 vpn
  neighbor 1.1.1.1 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0.0.0.0
 network 10.0.0.0/8 area 0.0.0.0
exit
!
mpls ldp
 !
 address-family ipv4
  discovery transport-address 3.3.3.3
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
end
