key = cisco123

user = cisco {
    default service = permit
    login = cleartext "cisco123"
    
    service = shell {
        priv-lvl = 15
    }
}
user = admin {
    default service = permit
    login = cleartext "admin"
    
    service = shell {
        priv-lvl = 15
    }
}
