frr version 10.5.1
frr defaults traditional
hostname vyos1
log syslog notifications
log timestamp precision 3
no log unique-id
service integrated-vtysh-config
!
interface eth1
 ip address 10.3.0.3/24
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 10.0.0.0/8 area 0.0.0.0
exit
!
